server:
  port: 8083

spring:
  application:
    name: life-note
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.92.79:8848
      config:
        prefix=example:
        file-extension: yaml
        group: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"