server:
  port: 9000

spring:
  application:
    name: life-gateway
  cloud:
    nacos:
      config:
        prefix=example:
        file-extension: yaml
        group: dev
      discovery:
        server-addr: 47.107.92.79:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: life
          uri: lb://life-base
          predicates:
            - Method=GET,POST,PUT,DELETE
        - id: life
          uri: lb://life-punch
          predicates:
            - Method=GET,POST,PUT,DELETE
        - id: life
          uri: lb://life-note
          predicates:
            - Method=GET,POST,PUT,DELETE
        - id: life
          uri: lb://life-mbook
          predicates:
            - Method=GET,POST,PUT,DELETE
        - id: life
          uri: lb://life-user
          predicates:
            - Method=GET,POST,PUT,DELETE

management:
  endpoints:
    web:
      exposure:
        include: "*"