spring:
  application:
    name: life-admin
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.92.79:8848

server:
  port: 8091


#开启端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
