spring:
  application:
    name: life-mbook
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        prefix=example:
        file-extension: yaml
        group: dev


server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"