server:
  port: 8081

spring:
  application:
    name: life-base
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        prefix=example:
        file-extension: yaml
        group: life-prod

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: life
    password: 1050lzy$
    url: jdbc:mysql://127.1.1.1:3306/life?useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
