server:
  port: 8085

spring:
  application:
    name: life-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        prefix=example:
        file-extension: yaml
        group: life-prod
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0


management:
  endpoints:
    web:
      exposure:
        include: "*"

wxmp:
  appIdd: wdx4d95cf331df5b4939f
  secret: d405dfe1a1df41f69941cc7bdb2f9