spring:
  application:
    name: life-mgt
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.92.79:8848
  redis:
    host: 106.13.139.156
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
